---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gateway
  name: gateway
  namespace: "openfaas-zhy"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
  selector:
    app: gateway
