---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: node-gateway
  name: node-gateway
  namespace: "openfaas-zhy"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: node-gateway
