---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: node-netes
  name: node-netes
  namespace: "openfaas-zhy"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: node-gateway
