---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: redis
  name: openfaas-zhy-redis
  namespace: "openfaas-zhy"
spec:
  type: NodePort
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 32190
  selector:
    app: redis
